[package]
name = "clusterpoi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
linfa = "0.7"
linfa-clustering = "0.7"
ndarray = "0.15"
anyhow = "1.0"
